linters:
  disable-all: true
  enable:
  {{- range .LinterList }}
    - {{ . }}
  {{- end }}

run:
  timeout: 5m
  tests: false

linters-settings:
  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithMessagef(
      - .WithStack(
      - github.com/rbee3u/gohelp/epkg

issues:
  exclude-rules:
    - linters:
        - exhaustive
      text: "missing cases in switch of type"
