name: build
on:
  pull_request:
  push:

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up golang
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run lint
        run: |
          make install-gcg
          make install-lint
          make lint
      - name: Run test
        run: |
          make test
